# your domain
domain: dajun1.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://github.com/cj200622550/proxypool/blob/master/config/source.yaml
